sonata_admin:
    title: 'Directory Admin'
    title_logo: favicon-16x16.png
    show_mosaic_button: false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        layout: 'admin/standard_layout.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.stats:
            contexts: [admin]
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

services:
    app.admin.member:
        class: App\Admin\MemberAdmin
        arguments: [~, App\Entity\Member, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Directory, label: 'Members' }

    app.admin.member_status:
        class: App\Admin\MemberStatusAdmin
        arguments: [~, App\Entity\MemberStatus, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Directory, label: 'Statuses' }

    app.admin.tag:
        class: App\Admin\TagAdmin
        arguments: [~, App\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Directory, label: 'Tags' }
        public: true

    app.admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: User }
        public: true
